
{{- range $k, $v := .Values.cronJobs.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $k }}
  labels:
    {{- include "misp.labels" $ | nindent 4 }}
spec:
  schedule: {{ $v.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: "{{ $.Values.cronJobs.image.repository }}:{{ $.Values.cronJobs.image.tag | default $.Chart.AppVersion }}"
            imagePullPolicy: {{ $.Values.cronJobs.image.pullPolicy }}
            command: {{ $v.commands}}
            volumeMounts:
              - name: bootstrap-config
                mountPath: /var/www/MISP/app/Config/bootstrap.php
                subPath: bootstrap.php
              - name: core-config
                mountPath: /var/www/MISP/app/Config/core.php
                subPath: core.php
              - name: application-config
                mountPath: /var/www/MISP/app/Config/config.php
                subPath: config.php
              - name: database-config
                mountPath: /var/www/MISP/app/Config/database.php
                subPath: database.php
          restartPolicy: OnFailure
          serviceAccountName: {{ include "misp.cronJobs.serviceAccountName" $ }}
          volumes:
            - name: database-config
              secret:
                secretName: {{ $.Values.config.databaseSecretName }}
            - name: application-config
              configMap:
                name: {{ $.Values.config.configConfigMapName }}
            - name: core-config
              configMap:
                name: {{ $.Values.config.coreConfigMapName }}
            - name: bootstrap-config
              configMap:
                name: {{ $.Values.config.bootstrapConfigMapName }}
{{- end }}