apiVersion: v1
kind: Service
metadata:
  name: {{ include "misp.fullname" . }}-frontend
  labels:
    {{- include "misp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "misp.frontend.selectorLabels" . | nindent 4 }}
