{{- if .Values.frontend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "misp.workers.serviceAccountName" . }}
  labels:
    {{- include "misp.labels" . | nindent 4 }}
  {{- with .Values.workers.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
