apiVersion: v1
kind: Service
metadata:
  name: misp-frontend
  labels:
    {{- include "misp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "misp.frontend.selectorLabels" . | nindent 4 }}
