apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "misp.fullname" . }}-modules
  labels:
    {{- include "misp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.modules.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "misp.modules.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "misp.modules.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "misp.modules.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.modules.image.repository }}:{{ .Values.modules.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.modules.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 6666
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /modules
              port: http
          readinessProbe:
            httpGet:
              path: /modules
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: REDIS_BACKEND
            value: {{ .Values.modules.config.redis_host}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}