{{- if .Values.modules.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "misp.modules.serviceAccountName" . }}
  labels:
    {{- include "misp.labels" . | nindent 4 }}
  {{- with .Values.modules.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
